[package]
name = "solstrale-desktop-rust"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"

[profile.release]
lto = true

[dependencies]
solstrale = { version = "0.1.10", features = ["oidn-postprocessor"] }
eframe = { version = "0.26.0", features = ["persistence", "wayland", "wgpu"] }
egui_file = "0.15.0"
image = "0.24.8"
serde = { version = "1.0.19", features = ["derive"] }
serde_yaml = "0.9.31"
enum-map = { version = "2.7.3", features = ["serde"] }
syntect = { version = "5.2.0", default-features = false, features = [
    "default-fancy",
] }
moka = { version = "0.12.5", features = ["sync"] }
once_cell = "1.19.0"
derive_more = "0.99.17"
hhmmss = "0.1.0"
regex = "1.10.3"
dark-light = "1.0.0"