[package]
name = "solstrale-desktop-rust"
version = "0.0.1"
edition = "2021"

[profile.release]
lto = true

[dependencies]
solstrale = "0.1.8"
eframe = { version = "0.22.0", features = ["persistence", "wayland", "wgpu"] }
egui_file = "0.10.0"
image = "0.24.5"
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
enum-map = { version = "2.5.0", features = ["serde"] }
syntect = { version = "5.0.0", default-features = false, features = [
    "default-fancy",
] }
moka = { version = "0.12.0", features = ["sync"] }
once_cell = "1.17.1"
derive_more = "0.99.17"
hhmmss = "0.1.0"
regex = "1.9.3"
dark-light = "1.0.0"