name: CI
on: [ push, pull_request ]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Clippy check
        run: cargo clippy
      - name: Test
        run: cargo test
